version: '3.8'

services:
  proxy-manager:
    build: .
    network_mode: "host"
    volumes:
      - ./settings.json:/app/settings.json
    environment:
      CHECK_AUTH: "true"
      AUTH_TOKEN: "auth_token" # when check auth set requires header Authorization with this value to all requests
      PORT: "25600"

